# Generated by Django 4.1.5 on 2023-01-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cart_id_alter_cartitems_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
