# Generated by Django 4.1.3 on 2023-01-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bannerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerproduct',
            name='price',
            field=models.FloatField(default=10.55),
        ),
    ]
